package edu.msu.cse476.msucompanion;

import android.os.Bundle;

import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import androidx.appcompat.app.AppCompatActivity;

import android.view.View;
import android.widget.EditText;
import android.widget.Toast;

import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.firestore.FirebaseFirestore;

import java.util.Date;
import java.util.Objects;

public class LoginActivity extends AppCompatActivity {

    private AppDatabase db;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_login);

        // Initialize local Room database for storing contacts and sessions after fetch
        db = AppDatabase.getInstance(this);
    }

    public void onLogin(View view) {
        // Input can be either an email or a username
        EditText inputEditText = findViewById(R.id.email);
        EditText passwordEditText = findViewById(R.id.password);

        String input = inputEditText.getText().toString().trim();
        String password = passwordEditText.getText().toString();

        if (input.isEmpty() || password.isEmpty()) {
            Toast.makeText(this, "Please fill in all fields", Toast.LENGTH_SHORT).show();
            return;
        }

        // Check if the input looks like an email or a username
        if (input.contains("@")) {
            signInWithEmail(input, password);
        } else {
            signInWithUsername(input, password);
        }
    }

    /*
     * Extracted into its own method so both the email path and
     * username path can call the same Firebase Auth sign in logic
     */
    private void signInWithEmail(String email, String password) {
        // Firebase Auth handles password verification securely
        // signInWithEmailAndPassword will fail automatically if credentials are wrong
        FirebaseAuth.getInstance().signInWithEmailAndPassword(email, password)
                .addOnSuccessListener(authResult -> {
                    // Auth succeeded — get the userID generated by Firebase
                    String uid = Objects.requireNonNull(authResult.getUser()).getUid();

                    // Fetch user profile (fullName, username) from Firestore
                    FirebaseFirestore.getInstance().collection(Keys.COLLECTION_USERS)
                            .document(uid)
                            .get()
                            .addOnSuccessListener(document -> {
                                // Pull full name and username from the Firestore user document
                                String fullName = document.getString(Keys.FIELD_USER_FULL_NAME);
                                String username = document.getString(Keys.FIELD_USER_USERNAME);

                                // Cache user profile locally in SharedPreferences
                                SharedPreferences prefs = getSharedPreferences(Keys.PREF_USER, Context.MODE_PRIVATE);
                                SharedPreferences.Editor editor = prefs.edit();
                                editor.putString(Keys.PREF_USER_ID, uid);
                                editor.putString(Keys.PREF_EMAIL, email);
                                editor.putString(Keys.PREF_FULL_NAME, fullName);
                                editor.putString(Keys.PREF_USERNAME, username);
                                editor.apply();

                                // Fetch contacts and session history from Firestore and store them in local database
                                fetchContacts(uid);
                                fetchSessionHistory(uid);

                                Toast.makeText(this, "Login Successful!", Toast.LENGTH_SHORT).show();

                                // Go to MainActivity and close LoginActivity
                                Intent intent = new Intent(this, MainActivity.class);
                                startActivity(intent);
                                finish();
                            })
                            .addOnFailureListener(e ->
                                    Toast.makeText(this, "Failed to fetch user data: " + e.getMessage(), Toast.LENGTH_LONG).show()
                            );
                })
                .addOnFailureListener(e ->
                        Toast.makeText(this, "Login Failed: " + e.getMessage(), Toast.LENGTH_LONG).show()
                );
    }

    private void signInWithUsername(String username, String password) {
        // Query Firestore to find the email linked to this username
        FirebaseFirestore.getInstance().collection(Keys.COLLECTION_USERS)
                .whereEqualTo(Keys.FIELD_USER_USERNAME, username)
                .get()
                .addOnSuccessListener(query -> {
                    if (!query.isEmpty()) {
                        // Found the user — grab their email and sign in with Firebase Auth
                        String foundEmail = query.getDocuments().get(0).getString(Keys.FIELD_USER_EMAIL);
                        signInWithEmail(foundEmail, password);
                    } else {
                        Toast.makeText(this, "Username not found", Toast.LENGTH_SHORT).show();
                    }
                })
                .addOnFailureListener(e ->
                        Toast.makeText(this, "Login Failed: " + e.getMessage(), Toast.LENGTH_LONG).show()
                );
    }

    /*
     * Fetches the user's contact list from Firestore and mirrors it
     * into the local Room database so contacts are available offline
     */
    private void fetchContacts(String uid) {
        FirebaseFirestore.getInstance().collection(Keys.COLLECTION_CONTACTS)
                .whereEqualTo(Keys.FIELD_USER_ID, uid)
                .get()
                .addOnSuccessListener(contacts -> new Thread(() -> {
                    // Clear existing local contacts first to avoid duplicates if the user logs in multiple times
                    db.contactDao().deleteAllByUserId(uid);

                    // Insert each contact from Firestore into local Room database
                    for (var doc : contacts.getDocuments()) {
                        String name = doc.getString(Keys.FIELD_CONTACT_NAME);
                        String phone = doc.getString(Keys.FIELD_CONTACT_PHONE);
                        String remoteId = doc.getId();

                        // remoteId links the local Room contact to the Firestore document
                        Contact contact = new Contact(remoteId, uid, name, phone);
                        db.contactDao().insert(contact);
                    }
                }).start())
                .addOnFailureListener(e ->
                        Toast.makeText(this, "Failed to fetch contacts: " + e.getMessage(), Toast.LENGTH_LONG).show()
                );
    }

    /*
     * Fetches the user's session history from Firestore and mirrors it
     * into the local Room database so sessions are available offline
     */
    private void fetchSessionHistory(String uid) {
        FirebaseFirestore.getInstance().collection(Keys.COLLECTION_SESSIONS)
                .whereEqualTo(Keys.FIELD_USER_ID, uid)
                .get()
                .addOnSuccessListener(sessions -> new Thread(() -> {
                    // Clear existing local sessions first to avoid duplicates if the user logs in multiple times
                    db.walkSessionDao().deleteAllByUserId(uid);

                    // Insert each session from Firestore into local Room database
                    for (var doc : sessions.getDocuments()) {
                        WalkSession session = new WalkSession();
                        session.setRemoteId(doc.getId());
                        session.setUserId(uid);
                        session.setDestinationName(doc.getString(Keys.FIELD_SESSION_DESTINATION_NAME));
                        session.setDestinationLat(doc.getDouble(Keys.FIELD_SESSION_DESTINATION_LAT));
                        session.setDestinationLng(doc.getDouble(Keys.FIELD_SESSION_DESTINATION_LNG));
                        session.setStartLat(doc.getDouble(Keys.FIELD_SESSION_START_LAT));
                        session.setStartLng(doc.getDouble(Keys.FIELD_SESSION_START_LNG));
                        session.setStatus(doc.getString(Keys.FIELD_SESSION_STATUS));

                        // Convert Firestore timestamps to Date objects
                        Date startTime = doc.getDate(Keys.FIELD_SESSION_START_TIME);
                        if (startTime != null) {
                            session.setStartTime(startTime);
                        }

                        Date endTime = doc.getDate(Keys.FIELD_SESSION_END_TIME);
                        if (endTime != null) {
                            session.setEndTime(endTime);
                        }

                        db.walkSessionDao().insert(session);
                    }
                }).start())
                .addOnFailureListener(e ->
                        Toast.makeText(this, "Failed to fetch session history: " + e.getMessage(), Toast.LENGTH_LONG).show()
                );
    }

    public void onSignUp(View view) {
        // Go to SignupActivity if user doesn't have an account
        Intent intent = new Intent(this, SignupActivity.class);
        startActivity(intent);
    }
}