package edu.msu.cse476.msucompanion;

import android.os.Bundle;

import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import androidx.appcompat.app.AppCompatActivity;

import android.view.View;
import android.widget.EditText;
import android.widget.Toast;

import com.google.firebase.auth.FirebaseAuth;

public class LoginActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_login);
    }

    public void onLogin(View view) {
        EditText emailEditText = findViewById(R.id.email);
        EditText passwordEditText = findViewById(R.id.password);
        // Grab email and password from the login page

        String email = emailEditText.getText().toString().trim();
        String password = passwordEditText.getText().toString();

        // Firebase Auth handles password verification securely, another free Google service
        // No need to query Firestore for password checking
        // signInWithEmailAndPassword will fail automatically if it is wrong
        FirebaseAuth.getInstance().signInWithEmailAndPassword(email, password)
                .addOnSuccessListener(authResult -> {
                    String uid = authResult.getUser().getUid();
                    // Auth succeeded, get the userID generated by Firebase


                    // Save to SharedPreferences (locally)
                    // app knows who is logged in without querying Firebase everytime
                    SharedPreferences prefs = getSharedPreferences("user_prefs", Context.MODE_PRIVATE);
                    SharedPreferences.Editor editor = prefs.edit();
                    editor.putString("userId", uid);
                    editor.putString("email", email);
                    editor.apply();

                    Toast.makeText(this, "Login Successful!", Toast.LENGTH_SHORT).show();

                    // Go to MainActivity and close LoginActivity

                    Intent intent = new Intent(this, MainActivity.class);
                    startActivity(intent);
                    finish(); //user can't go back, close LoginActivity
                })
                .addOnFailureListener(e -> {
                    Toast.makeText(this, "Login Failed: " + e.getMessage(), Toast.LENGTH_SHORT).show();
                });
    }

    public void onSignUp(View view) {
        // Go to SignupActivity if user doesn't have an account
        Intent intent = new Intent(this, SignupActivity.class);
        startActivity(intent);
    }
}